spring: 
  profiles: 
    active: 
    - dev 
    
---

spring: 
  profiles: dev 
  application: 
    name: microservicecloud-config-yxx-dev 
    
---

spring: 
  profiles: test 
  application: 
    name: microservicecloud-config-yxx-test
    