server:
  port: 9001
  
spring: 
  application:
    name: microservervicecloud-zuul-gateway
    
zuul:
  routes: 
    yxxdept.serviceId: microservicecloud-dept
    yxxdept.path: /yxxdept/**
  ignored-services: microservicecloud-dept
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/  
  instance:
    instance-id: gateway-9001.com
    prefer-ip-address: true
    
info: 
  app.name: yxx-depet
  company.name: www.yxx.com
  build.artifactId: microservicecloud-zuul-gateway-9001
  build.version: 0.0.1-SNAPSHOT  
  
  
  